CREATE ROLE rad LOGIN ENCRYPTED PASSWORD 'md5612abdce80cf2090a4bd8425c1bff79e'
  SUPERUSER CREATEDB CREATEROLE REPLICATION
  VALID UNTIL 'infinity';

CREATE DATABASE rad
  WITH ENCODING='UTF8'
       OWNER=rad
       CONNECTION LIMIT=-1;


CREATE extension postgis;